// app/console/src/pages/github/InviteLinks.vue
<script setup lang="ts">
import { computed, reactive, ref } from "vue";
import { TxCard } from "@talex-touch/tuffex/card";
import { TxDataTable } from "@talex-touch/tuffex/data-table";
import { TxButton, TxCopyButton } from "@talex-touch/tuffex/button";
import { TxStatusBadge } from "@talex-touch/tuffex/status-badge";
import { TxModal } from "@talex-touch/tuffex/modal";
import { TxForm, TxFormItem } from "@talex-touch/tuffex/form";
import { TxInput } from "@talex-touch/tuffex/input";
import { TxNumberInput } from "@talex-touch/tuffex/number-input";
import { TxSelect } from "@talex-touch/tuffex/select";
import { TxAlert } from "@talex-touch/tuffex/alert";
import { TxEmptyState } from "@talex-touch/tuffex/empty-state";
import { toast } from "@talex-touch/tuffex/utils";
import PageHeader from "../../components/PageHeader.vue";
import ErrorPanel from "../../components/ErrorPanel.vue";
import ErrorAlert from "../../components/ErrorAlert.vue";
import LoadingBlock from "../../components/LoadingBlock.vue";
import { api, jsonBody } from "../../lib/http";
import { confirm } from "../../lib/confirm";
import { fmtDate, fmtRelative } from "../../lib/format";
import { useOrg } from "../../lib/github";
import { useAction, useResource } from "../../lib/resource";
import { siteUrl } from "../../lib/runtime";

type Link = { token: string; note: string | null; max_uses: number; current_uses: number; expires_at: number; team_slug: string | null; disabled: number; created_by: string; created_at: number };
type Team = { name: string; slug: string };

const { apiBase } = useOrg();
const links = useResource(() => api<{ links: Link[] }>(`${apiBase.value}/invite-links`), [apiBase]);
const teams = useResource(() => api<{ teams: Team[] }>(`${apiBase.value}/teams`), [apiBase]);
const joinUrl = (token: string) => new URL(siteUrl("portal", `/join/${token}`), window.location.origin).toString();

function linkState(link: Link) {
  if (link.disabled) return { text: "已停用", status: "muted" as const };
  if (link.expires_at < Date.now()) return { text: "已过期", status: "danger" as const };
  if (link.current_uses >= link.max_uses) return { text: "次数用完", status: "warning" as const };
  return { text: "可用", status: "success" as const };
}

const columns = [
  { key: "link", title: "链接" },
  { key: "note", title: "备注", width: 160 },
  { key: "uses", title: "已用 / 上限", width: 110, align: "right" as const },
  { key: "expires", title: "到期", width: 150 },
  { key: "team", title: "自动加入团队", width: 130 },
  { key: "state", title: "状态", width: 100 },
  { key: "actions", title: "操作", width: 150, align: "right" as const },
];

const creating = ref(false);
const created = ref<string | null>(null);
const form = reactive({ hours: 72 as number | null, max_uses: 30 as number | null, note: "", team_slug: "" });
const teamOptions = computed(() => [{ value: "", label: "不加入团队" }, ...(teams.data.value?.teams ?? []).map(t => ({ value: t.slug, label: t.name, description: t.slug }))]);
function openCreate() {
  Object.assign(form, { hours: 72, max_uses: 30, note: "", team_slug: "" });
  created.value = null;
  create.reset();
  creating.value = true;
}
const create = useAction(async () => {
  const result = await api<{ token: string; url: string }>(`${apiBase.value}/invite-links`, {
    method: "POST",
    ...jsonBody({ hours: form.hours ?? 72, max_uses: form.max_uses ?? 30, note: form.note.trim(), team_slug: form.team_slug || null }),
  });
  created.value = result.url || joinUrl(result.token);
  await links.reload();
});
const toggle = useAction(async (link: Link) => {
  await api(`${apiBase.value}/invite-links/${link.token}`, { method: "PATCH", ...jsonBody({ disabled: !link.disabled }) });
  toast({ title: link.disabled ? "已启用" : "已停用", variant: "success" });
  await links.reload();
});
const remove = useAction(async (link: Link) => {
  await api(`${apiBase.value}/invite-links/${link.token}`, { method: "DELETE" });
  toast({ title: "已删除邀请链接", variant: "success" });
  await links.reload();
});
async function askRemove(link: Link) {
  if (await confirm({ title: "删除这条邀请链接？", body: "已经通过它发出的邀请不会撤回，只是以后不能再用这条链接。", confirmText: "删除", danger: true })) await remove.execute(link);
}
</script>

<template>
  <div class="page">
    <PageHeader title="邀请链接" description="生成一条有时限的链接发给新同学，对方填 GitHub 用户名后会自动收到组织邀请。">
      <template #actions>
        <TxButton variant="primary" icon="i-carbon-add" @click="openCreate">生成链接</TxButton>
      </template>
    </PageHeader>
    <ErrorAlert v-if="toggle.error.value" :error="toggle.error.value" @close="toggle.reset()" />
    <ErrorAlert v-if="remove.error.value" :error="remove.error.value" @close="remove.reset()" />

    <ErrorPanel v-if="links.error.value" :error="links.error.value" :retry="links.reload" />
    <LoadingBlock v-else-if="!links.data.value" :lines="6" />
    <TxCard v-else :padding="0">
      <TxDataTable style="--table-min: 1080px" :columns="columns" :data="links.data.value.links" row-key="token" table-layout="fixed" scroll-x>
        <template #cell-link="{ row }: { row: Link }">
          <span class="link-cell">
            <span class="mono ellipsis">/join/{{ row.token }}</span>
            <TxCopyButton :text="joinUrl(row.token)" copy-label="复制" copied-label="已复制" />
          </span>
        </template>
        <template #cell-note="{ row }: { row: Link }"><span :class="{ muted: !row.note }">{{ row.note || "无" }}</span></template>
        <template #cell-uses="{ row }: { row: Link }"><span class="num">{{ row.current_uses }} / {{ row.max_uses }}</span></template>
        <template #cell-expires="{ row }: { row: Link }">
          <span class="cell-stack"><span>{{ fmtRelative(row.expires_at) }}</span><span class="cell-sub">{{ fmtDate(row.expires_at) }}</span></span>
        </template>
        <template #cell-team="{ row }: { row: Link }"><span class="mono" :class="{ muted: !row.team_slug }">{{ row.team_slug ?? "无" }}</span></template>
        <template #cell-state="{ row }: { row: Link }"><TxStatusBadge :text="linkState(row).text" :status="linkState(row).status" size="sm" /></template>
        <template #cell-actions="{ row }: { row: Link }">
          <span class="row-actions">
            <TxButton size="sm" variant="ghost" :disabled="toggle.pending.value" @click="toggle.execute(row)">{{ row.disabled ? "启用" : "停用" }}</TxButton>
            <TxButton size="sm" variant="ghost" class="danger-text" :disabled="remove.pending.value" @click="askRemove(row)">删除</TxButton>
          </span>
        </template>
        <template #empty><TxEmptyState title="还没有邀请链接" description="用右上角的「生成链接」创建第一条。" size="small" /></template>
      </TxDataTable>
    </TxCard>

    <TxModal v-model="creating" :title="created ? '链接已生成' : '生成邀请链接'" width="min(92vw, 520px)">
      <template v-if="created">
        <TxAlert type="success" title="把下面的地址发给要邀请的同学" :closable="false" />
        <div class="created">
          <TxInput :model-value="created" readonly class="created__url" />
          <TxCopyButton :text="created" copy-label="复制" copied-label="已复制" size="md" />
        </div>
      </template>
      <TxForm v-else :model="form" label-position="top">
        <div class="form-grid">
          <TxFormItem label="有效时长（小时）">
            <TxNumberInput v-model="form.hours" :min="1" :max="8760" />
          </TxFormItem>
          <TxFormItem label="最多使用次数">
            <TxNumberInput v-model="form.max_uses" :min="1" :max="1000" />
          </TxFormItem>
          <TxFormItem label="备注（选填）" class="wide">
            <TxInput v-model="form.note" placeholder="例如：新生群" />
          </TxFormItem>
          <TxFormItem label="加入后自动进入团队" class="wide">
            <TxSelect v-model="form.team_slug" :options="teamOptions" class="fill-width" />
          </TxFormItem>
        </div>
        <ErrorAlert v-if="create.error.value" :error="create.error.value" @close="create.reset()" />
      </TxForm>
      <template #footer>
        <div class="dialog-actions">
          <TxButton v-if="created" variant="primary" @click="creating = false">完成</TxButton>
          <template v-else>
            <TxButton variant="secondary" @click="creating = false">取消</TxButton>
            <TxButton variant="primary" :loading="create.pending.value" @click="create.execute()">生成</TxButton>
          </template>
        </div>
      </template>
    </TxModal>
  </div>
</template>

<style scoped>
.link-cell {
  display: flex;
  align-items: center;
  gap: 8px;
  min-width: 0;
}
.num {
  font-variant-numeric: tabular-nums;
}
.row-actions {
  display: inline-flex;
  gap: 4px;
}
.danger-text {
  color: var(--tx-color-danger);
}
.created {
  display: flex;
  align-items: center;
  gap: 8px;
  margin-top: 12px;
}
.created__url {
  flex: 1;
  min-width: 0;
}
.dialog-actions {
  display: flex;
  justify-content: flex-end;
  gap: 8px;
}
</style>

// web/src/pages/admin/InviteLinks.tsx
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { useParams } from "react-router-dom";
import { api, fmtDate, fmtRelative } from "../../lib/api";
import { useConfirm } from "../../components/ConfirmDialog";
import Select from "../../components/Select";
import NumberInput from "../../components/NumberInput";

type Link = {
  token: string; org: string; created_by: string; note: string | null;
  max_uses: number; current_uses: number; expires_at: number;
  team_slug: string | null; disabled: number; created_at: number;
};

export default function InviteLinks() {
  const { org } = useParams();
  const qc = useQueryClient();
  const confirm = useConfirm();
  const { data, isLoading, error } = useQuery({
    queryKey: ["invite-links", org],
    queryFn: () => api<{ links: Link[] }>(`/api/admin/${org}/invite-links`),
  });
  const teams = useQuery({
    queryKey: ["teams-light", org],
    queryFn: () => api<{ teams: any[] }>(`/api/admin/${org}/teams`),
  });

  const [form, setForm] = useState({ hours: 24, max_uses: 30, note: "", team_slug: "" });
  const [created, setCreated] = useState<{ url: string; token: string } | null>(null);

  const create = useMutation({
    mutationFn: () => api<{ ok: boolean; token: string; url: string; expires_at: number }>(
      `/api/admin/${org}/invite-links`,
      { method: "POST", body: JSON.stringify({ ...form, team_slug: form.team_slug || null }) }
    ),
    onSuccess: (r) => { qc.invalidateQueries({ queryKey: ["invite-links", org] }); setCreated({ url: r.url, token: r.token }); },
  });
  const toggle = useMutation({
    mutationFn: ({ token, disabled }: { token: string; disabled: boolean }) =>
      api(`/api/admin/${org}/invite-links/${token}`, { method: "PATCH", body: JSON.stringify({ disabled }) }),
    onSuccess: () => qc.invalidateQueries({ queryKey: ["invite-links", org] }),
  });
  const del = useMutation({
    mutationFn: (token: string) => api(`/api/admin/${org}/invite-links/${token}`, { method: "DELETE" }),
    onSuccess: () => qc.invalidateQueries({ queryKey: ["invite-links", org] }),
  });

  const copy = (text: string) => navigator.clipboard.writeText(text);

  if (isLoading) return <div className="p-8 text-ink-500">加载中…</div>;
  if (error) return <div className="p-8 text-rose-400">{(error as Error).message}</div>;

  return (
    <div className="p-6 sm:p-8 max-w-7xl mx-auto space-y-8">
      <header>
        <h1 className="text-2xl font-semibold text-ink-50">邀请链接</h1>
        <p className="text-ink-400 text-sm mt-1">生成临时链接 → 发给目标 → 对方填 GitHub 用户名自动收到邀请</p>
      </header>

      <div className="card p-5">
        <h2 className="font-semibold text-ink-100 mb-4">生成新链接</h2>
        <div className="grid grid-cols-1 md:grid-cols-5 gap-3">
          <div>
            <label className="label text-xs">有效期（小时）</label>
            <NumberInput min={1} max={8760}
              value={form.hours} onChange={(v) => setForm({ ...form, hours: v })} />
          </div>
          <div>
            <label className="label text-xs">最大使用次数</label>
            <NumberInput min={1} max={1000}
              value={form.max_uses} onChange={(v) => setForm({ ...form, max_uses: v })} />
          </div>
          <div className="md:col-span-2">
            <label className="label text-xs">备注（方便识别）</label>
            <input className="input" placeholder="例：2024 级新生群"
              value={form.note} onChange={(e) => setForm({ ...form, note: e.target.value })} />
          </div>
          <div>
            <label className="label text-xs">自动加入 team（可选）</label>
            <Select
              value={form.team_slug}
              onChange={(v) => setForm({ ...form, team_slug: v })}
              options={[
                { value: "", label: "— 不绑定 —" },
                ...(teams.data?.teams ?? []).map((t: any) => ({ value: t.slug, label: t.name, hint: t.slug })),
              ]}
            />
          </div>
        </div>
        <button className="btn-primary mt-4" disabled={create.isPending} onClick={() => create.mutate()}>
          {create.isPending ? "生成中…" : "生成链接"}
        </button>
        {create.error && <div className="text-rose-400 text-sm mt-2">{(create.error as Error).message}</div>}

        {created && (
          <div className="mt-4 p-4 rounded-lg border border-emerald-500/40 bg-emerald-500/10">
            <div className="text-sm text-emerald-300 mb-2">链接已生成，复制下面 URL 发给目标</div>
            <div className="flex items-center gap-2">
              <input className="input font-mono text-xs flex-1" readOnly value={created.url} onClick={(e) => (e.target as HTMLInputElement).select()} />
              <button className="btn-ghost text-xs" onClick={() => copy(created.url)}>复制</button>
            </div>
          </div>
        )}
      </div>

      <div className="card overflow-hidden">
        <table className="w-full text-sm">
          <thead className="bg-ink-900/60 text-ink-400 text-xs uppercase tracking-wider">
            <tr>
              <th className="text-left px-5 py-3">链接</th>
              <th className="text-left px-5 py-3">备注</th>
              <th className="text-left px-5 py-3">使用</th>
              <th className="text-left px-5 py-3">到期</th>
              <th className="text-left px-5 py-3">Team</th>
              <th className="text-left px-5 py-3">状态</th>
              <th className="text-right px-5 py-3">操作</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-ink-800/60">
            {data!.links.length === 0 && <tr><td colSpan={7} className="px-5 py-8 text-center text-ink-500">还没有邀请链接</td></tr>}
            {data!.links.map((l) => {
              const fullUrl = `${location.origin}/join/${l.token}`;
              const expired = l.expires_at < Date.now();
              const usedUp = l.current_uses >= l.max_uses;
              return (
                <tr key={l.token} className="hover:bg-ink-800/30">
                  <td className="px-5 py-3">
                    <div className="flex items-center gap-2">
                      <code className="font-mono text-xs text-ink-300 truncate max-w-[180px]">/join/{l.token}</code>
                      <button className="text-xs text-brand-500 hover:underline" onClick={() => copy(fullUrl)}>复制</button>
                    </div>
                  </td>
                  <td className="px-5 py-3 text-ink-300 max-w-xs truncate">{l.note ?? "—"}</td>
                  <td className="px-5 py-3 text-ink-300">{l.current_uses}/{l.max_uses}</td>
                  <td className="px-5 py-3 text-ink-400 whitespace-nowrap text-xs">{fmtRelative(l.expires_at)}<br /><span className="text-ink-600">{fmtDate(l.expires_at)}</span></td>
                  <td className="px-5 py-3 font-mono text-xs text-ink-300">{l.team_slug ?? "—"}</td>
                  <td className="px-5 py-3">
                    {l.disabled ? <span className="tag-gray">disabled</span>
                      : expired ? <span className="tag-red">expired</span>
                      : usedUp ? <span className="tag-yellow">used up</span>
                      : <span className="tag-green">active</span>}
                  </td>
                  <td className="px-5 py-3 text-right space-x-2 whitespace-nowrap">
                    <button className="btn-ghost text-xs py-1 px-2"
                      onClick={() => toggle.mutate({ token: l.token, disabled: !l.disabled })}>
                      {l.disabled ? "启用" : "禁用"}
                    </button>
                    <button className="btn-danger text-xs py-1 px-2"
                      onClick={async () => {
                        const ok = await confirm({
                          title: "删除邀请链接",
                          body: `确定删除 /join/${l.token.slice(0, 12)}…？\n已通过此链接发出的邀请不会被撤回，只是后续不能再用这个链接。`,
                          confirmText: "删除",
                          variant: "danger",
                        });
                        if (ok) del.mutate(l.token);
                      }}>删除</button>
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>
    </div>
  );
}
